[book]
authors = ["Proximity Labs"]
language = "en"
multilingual = false
src = "src"
title = "The Omni Book"

[build]
create-missing = false

[output.html]
git-repository-url = "https://github.com/omni-rs/book"
edit-url-template = "https://github.com/omni-rs/book/edit/main/{path}"

[output.html.fold]
enable = true
level = 0
